name: chat_app
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  random_user: ^0.3.0
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.12.1
  uuid: ^2.2.2
  bubble: ^1.1.9+1
  intl: ^0.16.1




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
