name: chat_app
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_random_user : ^1.0.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.0
  riverpod_annotation:
  uuid: ^3.0.7
  bubble: ^1.2.1
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:
  freezed:
  flutter_lints:
  riverpod_lint:
  custom_lint:



dependency_overrides:
  http: ^0.13.5


flutter:
  uses-material-design: true
